[project]
name = "hexlet-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "uvicorn>=0.54.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "D"]
# Игнорируем конфликтующие правила, оставляя только те, что соответствуют Google Style
ignore = [
    "D203", # 1 blank line required before class docstring (конфликтует с D211)
    "D213", # Multi-line docstring summary should start at the second line (конфликтует с D212)
]

[tool.ruff.lint.pydocstyle]
convention = "google"